name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    
    strategy:
      matrix:
        elixir: ["1.14.5", "1.15.7", "1.16.2"]
        otp: ["25.3", "26.0"]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Compile
        run: mix compile --warnings-as-errors
      
      - name: Check formatting
        run: mix format --check-formatted
      
      - name: Run Credo
        run: mix credo --strict
      
      - name: Run tests
        run: mix test
        
  dialyzer:
    name: Run Dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.2"
          otp-version: "26.0"
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-dialyzer-
      
      - name: Restore PLT cache
        uses: actions/cache@v3
        with:
          path: priv/plts
          key: ${{ runner.os }}-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-dialyzer-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Create PLTs directory
        run: mkdir -p priv/plts
      
      - name: Run dialyzer
        run: mix dialyzer
        
  publish:
    name: Check package publishing
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.2"
          otp-version: "26.0"
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-publish-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-publish-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Build docs
        run: mix docs
      
      - name: Validate Hex package
        run: mix hex.build 